DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS gifts CASCADE;
DROP TABLE IF EXISTS selected_gifts CASCADE;
DROP TABLE IF EXISTS gifters CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE events (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  event_name VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  address VARCHAR (255),
  description VARCHAR (255)
);

CREATE TABLE gifts (
  id SERIAL PRIMARY KEY NOT NULL,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE,
  gift_name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  notes TEXT,
  store_url TEXT,
  quantity INTEGER NOT NULL,
  most_wanted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gifters (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE selected_gifts (
  id SERIAL PRIMARY KEY NOT NULL,
  selected_quantity INTEGER,
  gifter_id INTEGER REFERENCES gifters(id) ON DELETE CASCADE,
  gift_id INTEGER REFERENCES gifts(id) ON DELETE CASCADE
);
