DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS wishlist_gifts CASCADE;
DROP TABLE IF EXISTS gifters CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE events (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  event_name VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  address VARCHAR (255),
  description VARCHAR (255)
);

CREATE TABLE wishlist_gifts (
  id SERIAL PRIMARY KEY NOT NULL,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE,
  gift_name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  notes TEXT,
  store_url VARCHAR(255),
  quantity INTEGER NOT NULL,
  most_wanted BOOLEAN NOT NULL DEFAULT FALSE,
  reserved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE gifters (
  id SERIAL PRIMARY KEY NOT NULL,
  wishlist_gift_id INTEGER REFERENCES wishlist_gifts(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);
